services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/cybersec-pro
      - NODE_ENV=development

volumes:
  mongodb_data: