[build]
  command = "pnpm build"
  publish = ".next"

# Use the Next.js plugin for proper Netlify integration
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  # Provide default environment variables for build time
  MONGODB_URI = "mongodb://localhost:27017/unified-toolkit-build"
  JWT_SECRET = "build-time-jwt-secret-will-be-overridden-in-production"
  JWT_REFRESH_SECRET = "build-time-refresh-secret-will-be-overridden-in-production"
  NEXT_PUBLIC_SITE_URL = "https://app.netlify.com"

# Netlify Functions for API routes
[functions]
  directory = "netlify/functions"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
